$(() => {

    //tabs
    $(".c-title li:nth-child(1)").on("click", (() => {
        $(".c-body1").css("display", "block")
        $(".c-body2").css("display", "none")
        $(".c-body3").css("display", "none")
        $(".c-body4").css("display", "none")
        $(".c-body5").css("display", "none")
        $(".c-body6").css("display", "none")
        $(".c-body7").css("display", "none")
    }))
    $(".c-title li:nth-child(2)").on("click", (() => {
        $(".c-body1").css("display", "none")
        $(".c-body2").css("display", "block")
        $(".c-body3").css("display", "none")
        $(".c-body4").css("display", "none")
        $(".c-body5").css("display", "none")
        $(".c-body6").css("display", "none")
        $(".c-body7").css("display", "none")
    }))
    $(".c-title li:nth-child(3)").on("click", (() => {
        $(".c-body1").css("display", "none")
        $(".c-body2").css("display", "none")
        $(".c-body3").css("display", "block")
        $(".c-body4").css("display", "none")
        $(".c-body5").css("display", "none")
        $(".c-body6").css("display", "none")
        $(".c-body7").css("display", "none")
    }))
    $(".c-title li:nth-child(4)").on("click", (() => {
        $(".c-body1").css("display", "none")
        $(".c-body2").css("display", "none")
        $(".c-body3").css("display", "none")
        $(".c-body4").css("display", "block")
        $(".c-body5").css("display", "none")
        $(".c-body6").css("display", "none")
        $(".c-body7").css("display", "none")
    }))
    $(".c-title li:nth-child(5)").on("click", (() => {
        $(".c-body1").css("display", "none")
        $(".c-body2").css("display", "none")
        $(".c-body3").css("display", "none")
        $(".c-body4").css("display", "none")
        $(".c-body5").css("display", "block")
        $(".c-body6").css("display", "none")
        $(".c-body7").css("display", "none")
    }))
    $(".c-title li:nth-child(6)").on("click", (() => {
        $(".c-body1").css("display", "none")
        $(".c-body2").css("display", "none")
        $(".c-body3").css("display", "none")
        $(".c-body4").css("display", "none")
        $(".c-body5").css("display", "none")
        $(".c-body6").css("display", "block")
        $(".c-body7").css("display", "none")
    }))
    $(".c-title li:nth-child(7)").on("click", (() => {
        $(".c-body1").css("display", "none")
        $(".c-body2").css("display", "none")
        $(".c-body3").css("display", "none")
        $(".c-body4").css("display", "none")
        $(".c-body5").css("display", "none")
        $(".c-body6").css("display", "none")
        $(".c-body7").css("display", "block")
    }))
});
